name: Publish Notebook

on: 
  push:
    branches:
      - main # Or replace with the name of your default branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Convert Notebooks to HTML
        run: |
          mkdir html_output
          for notebook in $(find . -name '*.ipynb'); do
            jupyter nbconvert --to html $notebook --output-dir html_output
          done

      - name: Generate Index
        run: python ${{ github.workspace }}/generate_index.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/html_output
          publish_branch: gh-pages
